#!/usr/bin/env bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

### Display Setup
xrandr --output DP-2 --mode 1920x1080 --rate 144.00 --output HDMI-0 --mode 1920x1080 --rate 60.00 &

### Disable Screen Timeout ###
xset -dpms;
xset s off & 

### Wallpaper ###
feh --no-fehbg --bg-tile /mnt/HDD/Images/Wallpapers/BlissRet.jpg &
#feh --no-fehbg --bg-scale --no-xinerama /mnt/HDD/Images/Wallpapers/StarrySky1440p.jpg &

### Mouse Settings ###
~/scripts/mousesettings

### Compositor ###
killall -q picom;
picom --experimental-backends &

### Udiskie ###
killall -q udiskie;
udiskie &

### LeftWM Theme ###
leftwm-command "LoadTheme $SCRIPTPATH/theme.toml" &

### Tiramisu ###
#killall -q tiramisu &

### Eww ###
killall -q eww;
eww open-many bar1 bar2 &

### Bluetooth ###
killall -q blueman-applet;
blueman-applet &
while ! bluetoothctl connect 5C:C6:E9:14:A8:15;
do sleep 1;
done &

### Discord ###
discocss &
