#!/usr/bin/env bash

### Autostart ###
run() {
	if ! pgrep -f "$1"; then
		"$@"&
	fi
}

# Wallpaper #
run ~/scripts/wallpapersetter

# Compositor #
run picom --experimental-backends

# Bluetooth #
run blueman-applet

# Eww #
run ~/eww/target/release/eww open bar

# Discord #
if pgrep -f discord; then
	exit &
else
	discocss &
fi

### Herbstluft Config ###
hc() {
	herbstclient "$@"
}

hc emit_hook reload

# keybinds
hc keyunbind --all
Mod=Mod4
hc keybind $Mod-Shift-q quit
hc keybind $Mod-q reload
hc keybind $Mod-Shift-c close_and_remove
hc keybind $Mod-Shift-Return spawn "${TERMINAL:-alacritty}"
hc keybind $Mod-Return spawn alacritty --class 'Alacritty,scratchpad'
hc keybind $Mod-Shift-Escape spawn alacritty --class 'Alacritty,bottom' -e btm
hc keybind $Mod-p spawn rofi -show drun
hc keybind XF86AudioRaiseVolume spawn ~/scripts/volume -u
hc keybind XF86AudioLowerVolume spawn ~/scripts/volume -d
hc keybind XF86AudioMute spawn ~/scripts/volume -m

# basic movement in tiling and floating mode focusing clients
hc keybind $Mod-Left focus left
hc keybind $Mod-Down focus down
hc keybind $Mod-Up focus up
hc keybind $Mod-Right focus right
hc keybind $Mod-h focus left
hc keybind $Mod-j focus down
hc keybind $Mod-k focus up
hc keybind $Mod-l focus right

# moving clients in tiling and floating mode
hc keybind $Mod-Shift-Control-Left shift left
hc keybind $Mod-Shift-Control-Down shift down
hc keybind $Mod-Shift-Control-Up shift up
hc keybind $Mod-Shift-Control-Right shift right
hc keybind $Mod-Shift-Control-h shift left
hc keybind $Mod-Shift-Control-j shift down
hc keybind $Mod-Shift-Control-k shift up
hc keybind $Mod-Shift-Control-l shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-u split bottom 0.5
hc keybind $Mod-o split right 0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames and floating clients
resizestep=0.0492
hc keybind $Mod-Shift-h resize left +$resizestep
hc keybind $Mod-Shift-j resize down +$resizestep
hc keybind $Mod-Shift-k resize up +$resizestep
hc keybind $Mod-Shift-l resize right +$resizestep
hc keybind $Mod-Shift-Left resize left +$resizestep
hc keybind $Mod-Shift-Down resize down +$resizestep
hc keybind $Mod-Shift-Up resize up +$resizestep
hc keybind $Mod-Shift-Right resize right +$resizestep

# tags
tag_names=( {1..5} )
tag_keys=( {1..5} 0 )

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
	hc add "${tag_names[$i]}"
	key="${tag_keys[$i]}"
	if [ -n "$key" ] ; then
		hc keybind "$Mod-$key" use_index "$i"
		hc keybind "$Mod-Shift-$key" move_index "$i"
  fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-Shift-f set_attr clients.focus.floating toggle
hc keybind $Mod-Shift-d set_attr clients.focus.decorated toggle
hc keybind $Mod-Shift-m set_attr clients.focus.minimized true
hc keybind $Mod-Control-m jumpto last-minimized
#hc keybind $Mod-p pseudotile toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space \
	or , and . compare tags.focus.curframe_wcount = 2 \
	. cycle_layout +1 vertical horizontal max vertical grid \
	, cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize
hc set focus_follows_mouse true

# focus
hc keybind $Mod-BackSpace cycle_monitor
hc keybind $Mod-Tab cycle_all +1
hc keybind $Mod-Shift-Tab cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#222222'
hc set frame_border_normal_color '#101010'
hc set frame_bg_normal_color '#262727'
hc set frame_bg_active_color '#f5d1c8'
hc set frame_border_width 0
hc set show_frame_decorations 'focused_if_multiple'
hc set frame_bg_transparent on
hc set frame_transparent_width 0
hc set frame_gap 0

hc attr theme.title_height 0
hc attr theme.title_when always
hc attr theme.title_font 'monospace:bold:pixelsize=16'  # example using Xft
# hc attr theme.title_font '-*-fixed-medium-r-*-*-13-*-*-*-*-*-*-*'
hc attr theme.title_depth 3  # space below the title's baseline
hc attr theme.active.color '#f5d1c8'
hc attr theme.title_color '#262727'
hc attr theme.normal.color '#262727'
hc attr theme.normal.title_color '#f5d1c8'
hc attr theme.urgent.color '#7811A1dd'
hc attr theme.tab_color '#262727'
hc attr theme.active.tab_color '#262727'
hc attr theme.active.tab_title_color '#f5d1c8'
hc attr theme.active.tab_outer_color '#262727'
hc attr theme.title_align center
hc attr theme.inner_width 0
hc attr theme.inner_color black
hc attr theme.border_width 4
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color '#f5d1c8'
hc attr theme.active.inner_color '#f5d1c8'
hc attr theme.urgent.inner_color '#9A65B0'
hc attr theme.normal.inner_color '#262727'
# copy inner color to outer_color
for state in active urgent normal ; do
	hc substitute C theme.${state}.inner_color \
		attr theme.${state}.outer_color C
done
hc attr theme.tiling.outer_width 1
hc attr theme.background_color '#141414'

hc set window_gap 20
hc set frame_padding 0
hc set smart_window_surroundings off
hc set smart_frame_surroundings off
hc set mouse_recenter_gap 0

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
hc rule floatplacement=center
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
hc rule fixedsize floating=on
hc rule class=discord tag=2
hc rule class=scratchpad floating=on
hc rule class=bottom floating=on

hc set tree_style '╾│ ├└╼─┐'

# unlock, just to be sure
hc unlock

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
hc detect_monitors
