#!/bin/sh

areashot () {	
	maim -usb 2 /tmp/clipboard.png; sleep .1; xclip -selection clipboard < /tmp/clipboard.png -t image/png && notify-send -i /tmp/clipboard.png 'Screenshot' 'Selection Captured'
}

fullshot () {
	maim -u /tmp/clipboard.png; sleep .1; xclip -selection clipboard < /tmp/clipboard.png -t image/png && notify-send -i /tmp/clipboard.png 'Screenshot' 'Screenshot Captured'
}

while getopts af flag; do
	case "$flag" in
		a) areashot;;
		f) fullshot;;
	esac
done
