" Name:         Dark
" Description:  Template for dark colorscheme
" Author:       Myself <myself@somewhere.org>
" Maintainer:   Myself <myself@somewhere.org>
" Website:      https://me.org
" License:      Public domain
" Last Updated: Wed 21 Jul 2021 10:15:41 PM PDT

" Generated by Colortemplate v2.1.0

set background=dark

hi clear
let g:colors_name = 'dark'

let s:t_Co = exists('&t_Co') && !empty(&t_Co) && &t_Co > 1 ? &t_Co : 2
let s:italics = (&t_ZH != '' && &t_ZH != '[7m') || has('gui_running')

hi! link Boolean Constant
hi! link Character Constant
hi! link Conditional Statement
hi! link Debug Special
hi! link Define PreProc
hi! link Delimiter Special
hi! link Exception Statement
hi! link Float Constant
hi! link Function Identifier
hi! link Include PreProc
hi! link Keyword Statement
hi! link Label Statement
hi! link Macro PreProc
hi! link Number Constant
hi! link Operator Statement
hi! link PopupSelected PmenuSel
hi! link PreCondit PreProc
hi! link QuickFixLine Search
hi! link Repeat Statement
hi! link SpecialChar Special
hi! link SpecialComment Special
hi! link StatusLineTerm StatusLine
hi! link StatusLineTermNC StatusLineNC
hi! link StorageClass Type
hi! link String Constant
hi! link Structure Type
hi! link Tag Special
hi! link Typedef Type
hi! link lCursor Cursor

if (has('termguicolors') && &termguicolors) || has('gui_running')
  let g:terminal_ansi_colors = ['#262727', '#ff8278', '#bde077', '#eadc84', '#77bee0', '#dd91f3', '#ffc178', '#f5d1c8', '#555657', '#ff8278', '#bde077', '#eadc84', '#77bee0', '#dd91f3', '#ffc178', '#dddddd']
  if get(g:, 'dark_transp_bg', 0) && !has('gui_running')
    hi Normal guifg=#dddddd guibg=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#dddddd guibg=NONE gui=NONE cterm=NONE
  else
    hi Normal guifg=#dddddd guibg=#262727 gui=NONE cterm=NONE
    hi Terminal guifg=#dddddd guibg=#262727 gui=NONE cterm=NONE
  endif
  hi ColorColumn guifg=NONE guibg=#555657 gui=NONE cterm=NONE
  hi Conceal guifg=NONE guibg=#555657 gui=NONE cterm=NONE
  hi Cursor guifg=#262727 guibg=#f5d1c8 gui=NONE cterm=NONE
  hi CursorColumn guifg=NONE guibg=#555657 gui=NONE cterm=NONE
  hi CursorLine guifg=NONE guibg=#262727 gui=NONE cterm=NONE
  hi CursorLineNr guifg=#f5d1c8 guibg=#262727 gui=NONE cterm=NONE
  hi DiffAdd guifg=#f5d1c8 guibg=#262727 gui=reverse cterm=reverse
  hi DiffChange guifg=#f5d1c8 guibg=#262727 gui=reverse cterm=reverse
  hi DiffDelete guifg=#f5d1c8 guibg=#262727 gui=reverse cterm=reverse
  hi DiffText guifg=#f5d1c8 guibg=#262727 gui=bold,reverse cterm=bold,reverse
  hi Directory guifg=#f5d1c8 guibg=#262727 gui=NONE cterm=NONE
  hi EndOfBuffer guifg=#f5d1c8 guibg=#262727 gui=NONE cterm=NONE
  hi ErrorMsg guifg=#262727 guibg=#ff8278 gui=reverse cterm=reverse
  hi FoldColumn guifg=NONE guibg=#555657 gui=NONE cterm=NONE
  hi Folded guifg=#555657 guibg=#262727 gui=italic cterm=italic
  hi IncSearch guifg=#f5d1c8 guibg=#262727 gui=standout cterm=reverse
  hi LineNr guifg=#555657 guibg=#262727 gui=NONE cterm=NONE
  hi MatchParen guifg=#f5d1c8 guibg=#262727 gui=NONE cterm=NONE
  hi ModeMsg guifg=#f5d1c8 guibg=#262727 gui=NONE cterm=NONE
  hi MoreMsg guifg=#f5d1c8 guibg=#262727 gui=NONE cterm=NONE
  hi NonText guifg=#f5d1c8 guibg=#262727 gui=NONE cterm=NONE
  hi Pmenu guifg=#f5d1c8 guibg=#262727 gui=NONE cterm=NONE
  hi PmenuSbar guifg=#f5d1c8 guibg=#262727 gui=NONE cterm=NONE
  hi PmenuSel guifg=#f5d1c8 guibg=#262727 gui=reverse cterm=reverse
  hi PmenuThumb guifg=#f5d1c8 guibg=#262727 gui=NONE cterm=NONE
  hi Question guifg=#f5d1c8 guibg=#262727 gui=NONE cterm=NONE
  hi Search guifg=#262727 guibg=#555657 gui=NONE cterm=NONE
  hi SignColumn guifg=#f5d1c8 guibg=#262727 gui=NONE cterm=NONE
  hi SpecialKey guifg=#f5d1c8 guibg=#262727 gui=NONE cterm=NONE
  hi SpellBad guifg=#f5d1c8 guibg=#262727 guisp=#ff8278 gui=NONE cterm=NONE
  hi SpellCap guifg=#f5d1c8 guibg=#262727 guisp=#77bee0 gui=NONE cterm=NONE
  hi SpellLocal guifg=#f5d1c8 guibg=#262727 guisp=#dd91f3 gui=NONE cterm=NONE
  hi SpellRare guifg=#f5d1c8 guibg=#262727 guisp=#ffc178 gui=reverse cterm=reverse
  hi StatusLine guifg=#262727 guibg=#262727 gui=NONE cterm=NONE
  hi StatusLineNC guifg=#f5d1c8 guibg=#262727 gui=NONE cterm=NONE
  hi TabLine guifg=#f5d1c8 guibg=#262727 gui=NONE cterm=NONE
  hi TabLineFill guifg=#f5d1c8 guibg=#262727 gui=NONE cterm=NONE
  hi TabLineSel guifg=#f5d1c8 guibg=#262727 gui=NONE cterm=NONE
  hi Title guifg=#f5d1c8 guibg=#262727 gui=NONE cterm=NONE
  hi VertSplit guifg=#f5d1c8 guibg=#262727 gui=NONE cterm=NONE
  hi Visual guifg=#dddddd guibg=#555657 gui=NONE cterm=NONE
  hi VisualNOS guifg=#f5d1c8 guibg=#262727 gui=NONE cterm=NONE
  hi WarningMsg guifg=#ff8278 guibg=#262727 gui=NONE cterm=NONE
  hi WildMenu guifg=#f5d1c8 guibg=#262727 gui=NONE cterm=NONE
  hi Comment guifg=#555657 guibg=#262727 gui=italic cterm=italic
  hi Constant guifg=#ff8278 guibg=#262727 gui=NONE cterm=NONE
  hi Error guifg=#262727 guibg=#ff8278 gui=reverse cterm=reverse
  hi Identifier guifg=#77bee0 guibg=#262727 gui=NONE cterm=NONE
  hi Ignore guifg=#dddddd guibg=#262727 gui=NONE cterm=NONE
  hi PreProc guifg=#dd91f3 guibg=#262727 gui=NONE cterm=NONE
  hi Special guifg=#ffc178 guibg=#262727 gui=NONE cterm=NONE
  hi Statement guifg=#eadc84 guibg=#262727 gui=NONE cterm=NONE
  hi Todo guifg=#77bee0 guibg=#eadc84 gui=NONE cterm=NONE
  hi Type guifg=#bde077 guibg=#262727 gui=NONE cterm=NONE
  hi Underlined guifg=#77bee0 guibg=#262727 gui=NONE cterm=NONE
  hi CursorIM guifg=NONE guibg=fg gui=NONE cterm=NONE
  hi ToolbarLine guifg=NONE guibg=#262727 gui=NONE cterm=NONE
  hi ToolbarButton guifg=#f5d1c8 guibg=#262727 gui=bold cterm=bold
  hi IndentBlankLineChar guifg=#555657 guibg=NONE gui=NONE cterm=NONE
  hi IndentBlankLineSpaceChar guifg=#555657 guibg=NONE gui=NONE cterm=NONE
  if !s:italics
    hi Folded gui=NONE cterm=NONE
    hi Comment gui=NONE cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 256
  if get(g:, 'dark_transp_bg', 0)
    hi Normal ctermfg=15 ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=15 ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=15 ctermbg=0 cterm=NONE
    hi Terminal ctermfg=15 ctermbg=0 cterm=NONE
  endif
  hi ColorColumn ctermfg=NONE ctermbg=8 cterm=NONE
  hi Conceal ctermfg=NONE ctermbg=8 cterm=NONE
  hi Cursor ctermfg=0 ctermbg=7 cterm=NONE
  hi CursorColumn ctermfg=NONE ctermbg=8 cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=0 cterm=NONE
  hi CursorLineNr ctermfg=7 ctermbg=0 cterm=NONE
  hi DiffAdd ctermfg=7 ctermbg=0 cterm=reverse
  hi DiffChange ctermfg=7 ctermbg=0 cterm=reverse
  hi DiffDelete ctermfg=7 ctermbg=0 cterm=reverse
  hi DiffText ctermfg=7 ctermbg=0 cterm=bold,reverse
  hi Directory ctermfg=7 ctermbg=0 cterm=NONE
  hi EndOfBuffer ctermfg=7 ctermbg=0 cterm=NONE
  hi ErrorMsg ctermfg=0 ctermbg=1 cterm=reverse
  hi FoldColumn ctermfg=NONE ctermbg=8 cterm=NONE
  hi Folded ctermfg=8 ctermbg=0 cterm=italic
  hi IncSearch ctermfg=7 ctermbg=0 cterm=reverse
  hi LineNr ctermfg=8 ctermbg=0 cterm=NONE
  hi MatchParen ctermfg=7 ctermbg=0 cterm=NONE
  hi ModeMsg ctermfg=7 ctermbg=0 cterm=NONE
  hi MoreMsg ctermfg=7 ctermbg=0 cterm=NONE
  hi NonText ctermfg=7 ctermbg=0 cterm=NONE
  hi Pmenu ctermfg=7 ctermbg=0 cterm=NONE
  hi PmenuSbar ctermfg=7 ctermbg=0 cterm=NONE
  hi PmenuSel ctermfg=7 ctermbg=0 cterm=reverse
  hi PmenuThumb ctermfg=7 ctermbg=0 cterm=NONE
  hi Question ctermfg=7 ctermbg=0 cterm=NONE
  hi Search ctermfg=0 ctermbg=8 cterm=NONE
  hi SignColumn ctermfg=7 ctermbg=0 cterm=NONE
  hi SpecialKey ctermfg=7 ctermbg=0 cterm=NONE
  hi SpellBad ctermfg=7 ctermbg=0 cterm=NONE
  hi SpellCap ctermfg=7 ctermbg=0 cterm=NONE
  hi SpellLocal ctermfg=7 ctermbg=0 cterm=NONE
  hi SpellRare ctermfg=7 ctermbg=0 cterm=reverse
  hi StatusLine ctermfg=0 ctermbg=0 cterm=NONE
  hi StatusLineNC ctermfg=7 ctermbg=0 cterm=NONE
  hi TabLine ctermfg=7 ctermbg=0 cterm=NONE
  hi TabLineFill ctermfg=7 ctermbg=0 cterm=NONE
  hi TabLineSel ctermfg=7 ctermbg=0 cterm=NONE
  hi Title ctermfg=7 ctermbg=0 cterm=NONE
  hi VertSplit ctermfg=7 ctermbg=0 cterm=NONE
  hi Visual ctermfg=15 ctermbg=8 cterm=NONE
  hi VisualNOS ctermfg=7 ctermbg=0 cterm=NONE
  hi WarningMsg ctermfg=1 ctermbg=0 cterm=NONE
  hi WildMenu ctermfg=7 ctermbg=0 cterm=NONE
  hi Comment ctermfg=8 ctermbg=0 cterm=italic
  hi Constant ctermfg=1 ctermbg=0 cterm=NONE
  hi Error ctermfg=0 ctermbg=1 cterm=reverse
  hi Identifier ctermfg=4 ctermbg=0 cterm=NONE
  hi Ignore ctermfg=15 ctermbg=0 cterm=NONE
  hi PreProc ctermfg=5 ctermbg=0 cterm=NONE
  hi Special ctermfg=6 ctermbg=0 cterm=NONE
  hi Statement ctermfg=3 ctermbg=0 cterm=NONE
  hi Todo ctermfg=4 ctermbg=3 cterm=NONE
  hi Type ctermfg=2 ctermbg=0 cterm=NONE
  hi Underlined ctermfg=4 ctermbg=0 cterm=NONE
  hi CursorIM ctermfg=NONE ctermbg=fg cterm=NONE
  hi ToolbarLine ctermfg=NONE ctermbg=0 cterm=NONE
  hi ToolbarButton ctermfg=7 ctermbg=0 cterm=bold
  hi IndentBlankLineChar ctermfg=8 ctermbg=NONE cterm=NONE
  hi IndentBlankLineSpaceChar ctermfg=8 ctermbg=NONE cterm=NONE
  if !s:italics
    hi Folded cterm=NONE
    hi Comment cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 8
  if get(g:, 'dark_transp_bg', 0)
    hi Normal ctermfg=White ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=White ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=White ctermbg=Black cterm=NONE
    hi Terminal ctermfg=White ctermbg=Black cterm=NONE
  endif
  hi ColorColumn ctermfg=NONE ctermbg=DarkGrey cterm=NONE
  hi Conceal ctermfg=NONE ctermbg=DarkGrey cterm=NONE
  hi Cursor ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi CursorColumn ctermfg=NONE ctermbg=DarkGrey cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=Black cterm=NONE
  hi CursorLineNr ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi DiffAdd ctermfg=LightGrey ctermbg=Black cterm=reverse
  hi DiffChange ctermfg=LightGrey ctermbg=Black cterm=reverse
  hi DiffDelete ctermfg=LightGrey ctermbg=Black cterm=reverse
  hi DiffText ctermfg=LightGrey ctermbg=Black cterm=bold,reverse
  hi Directory ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi EndOfBuffer ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi ErrorMsg ctermfg=Black ctermbg=DarkRed cterm=reverse
  hi FoldColumn ctermfg=NONE ctermbg=DarkGrey cterm=NONE
  hi Folded ctermfg=DarkGrey ctermbg=Black cterm=italic
  hi IncSearch ctermfg=LightGrey ctermbg=Black cterm=reverse
  hi LineNr ctermfg=DarkGrey ctermbg=Black cterm=NONE
  hi MatchParen ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi ModeMsg ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi MoreMsg ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi NonText ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi Pmenu ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi PmenuSbar ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi PmenuSel ctermfg=LightGrey ctermbg=Black cterm=reverse
  hi PmenuThumb ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi Question ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi Search ctermfg=Black ctermbg=DarkGrey cterm=NONE
  hi SignColumn ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi SpecialKey ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi SpellBad ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi SpellCap ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi SpellLocal ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi SpellRare ctermfg=LightGrey ctermbg=Black cterm=reverse
  hi StatusLine ctermfg=Black ctermbg=Black cterm=NONE
  hi StatusLineNC ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi TabLine ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi TabLineFill ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi TabLineSel ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi Title ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi VertSplit ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi Visual ctermfg=White ctermbg=DarkGrey cterm=NONE
  hi VisualNOS ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi WarningMsg ctermfg=DarkRed ctermbg=Black cterm=NONE
  hi WildMenu ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi Comment ctermfg=DarkGrey ctermbg=Black cterm=italic
  hi Constant ctermfg=DarkRed ctermbg=Black cterm=NONE
  hi Error ctermfg=Black ctermbg=DarkRed cterm=reverse
  hi Identifier ctermfg=DarkBlue ctermbg=Black cterm=NONE
  hi Ignore ctermfg=White ctermbg=Black cterm=NONE
  hi PreProc ctermfg=DarkMagenta ctermbg=Black cterm=NONE
  hi Special ctermfg=DarkCyan ctermbg=Black cterm=NONE
  hi Statement ctermfg=DarkYellow ctermbg=Black cterm=NONE
  hi Todo ctermfg=DarkBlue ctermbg=DarkYellow cterm=NONE
  hi Type ctermfg=DarkGreen ctermbg=Black cterm=NONE
  hi Underlined ctermfg=DarkBlue ctermbg=Black cterm=NONE
  hi CursorIM ctermfg=NONE ctermbg=fg cterm=NONE
  hi ToolbarLine ctermfg=NONE ctermbg=Black cterm=NONE
  hi ToolbarButton ctermfg=LightGrey ctermbg=Black cterm=bold
  hi IndentBlankLineChar ctermfg=DarkGrey ctermbg=NONE cterm=NONE
  hi IndentBlankLineSpaceChar ctermfg=DarkGrey ctermbg=NONE cterm=NONE
  if !s:italics
    hi Folded cterm=NONE
    hi Comment cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 2
  hi Normal term=NONE
  hi ColorColumn term=reverse
  hi Conceal term=NONE
  hi Cursor term=NONE
  hi CursorColumn term=reverse
  hi CursorLine term=underline
  hi CursorLineNr term=bold,italic,reverse,underline
  hi DiffAdd term=reverse,underline
  hi DiffChange term=reverse,underline
  hi DiffDelete term=reverse,underline
  hi DiffText term=bold,reverse,underline
  hi Directory term=NONE
  hi EndOfBuffer term=NONE
  hi ErrorMsg term=bold,italic,reverse
  hi FoldColumn term=reverse
  hi Folded term=italic,reverse,underline
  hi IncSearch term=bold,italic,reverse
  hi LineNr term=reverse
  hi MatchParen term=bold,underline
  hi ModeMsg term=NONE
  hi MoreMsg term=NONE
  hi NonText term=NONE
  hi Pmenu term=reverse
  hi PmenuSbar term=NONE
  hi PmenuSel term=NONE
  hi PmenuThumb term=NONE
  hi PopupSelected term=reverse
  hi Question term=standout
  hi Search term=italic,underline
  hi SignColumn term=reverse
  hi SpecialKey term=bold
  hi SpellBad term=italic,underline
  hi SpellCap term=italic,underline
  hi SpellLocal term=italic,underline
  hi SpellRare term=italic,underline
  hi StatusLine term=bold,reverse
  hi StatusLineNC term=reverse
  hi TabLine term=italic,reverse,underline
  hi TabLineFill term=reverse,underline
  hi TabLineSel term=bold
  hi Title term=bold
  hi VertSplit term=reverse
  hi Visual term=reverse
  hi VisualNOS term=NONE
  hi WarningMsg term=standout
  hi WildMenu term=bold
  hi Comment term=italic
  hi Constant term=bold,italic
  hi Error term=reverse
  hi Identifier term=italic
  hi Ignore term=NONE
  hi PreProc term=italic
  hi Special term=bold,italic
  hi Statement term=bold
  hi Todo term=bold,underline
  hi Type term=bold
  hi Underlined term=underline
  hi CursorIM term=NONE
  hi ToolbarLine term=reverse
  hi ToolbarButton term=bold,reverse
  if !s:italics
    hi CursorLineNr term=bold,reverse,underline
    hi ErrorMsg term=bold,reverse
    hi Folded term=reverse,underline
    hi IncSearch term=bold,reverse
    hi Search term=underline
    hi SpellBad term=underline
    hi SpellCap term=underline
    hi SpellLocal term=underline
    hi SpellRare term=underline
    hi TabLine term=reverse,underline
    hi Comment term=NONE
    hi Constant term=bold
    hi Identifier term=NONE
    hi PreProc term=NONE
    hi Special term=bold
  endif
  unlet s:t_Co s:italics
  finish
endif

" Background: dark
" Color: black         #262727           0                 Black
" Color: red           #ff8278           1                 DarkRed
" Color: green         #bde077           2                 DarkGreen
" Color: yellow        #eadc84           3                 DarkYellow
" Color: blue          #77bee0           4                 DarkBlue
" Color: magenta       #dd91f3           5                 DarkMagenta
" Color: cyan          #ffc178           6                 DarkCyan
" Color: white         #f5d1c8           7                 LightGrey
" Color: brightblack   #555657           8                 DarkGrey
" Color: brightred     #ff8278           9                 LightRed
" Color: brightgreen   #bde077           10                LightGreen
" Color: brightyellow  #eadc84           11                LightYellow
" Color: brightblue    #77bee0           12                LightBlue
" Color: brightmagenta #dd91f3           13                LightMagenta
" Color: brightcyan    #ffc178           14                LightCyan
" Color: brightwhite   #dddddd           15                White
" Term colors: black red green yellow blue magenta cyan white
" Term colors: brightblack brightred brightgreen brightyellow
" Term colors: brightblue brightmagenta brightcyan brightwhite
" vim: et ts=2 sw=2
