#!/usr/bin/env bash

### Autostart ###
run() {
	if ! pgrep -f "$1"; then
		"$@"&
	fi
}
### SXHKD ###
killall sxhkd;
sxhkd &

### Wallpaper ###
run ~/scripts/wallpapersetter

### Compositor ###
run picom --experimental-backends

### Bluetooth ###
run blueman-applet

### Eww ###
run ~/eww/target/release/eww open bar

### Discord ###
if pgrep -f discord; then
	exit &
else
	discocss &
fi

###  BSPWM Cursor ###
xsetroot -cursor_name left_ptr &

### BSPWM Monitor Setup ###
bspc monitor DP-2 -d 1 3 4 5
bspc monitor HDMI-0 -d 2

### BSPWM Config ###
bspc config focus_follows_pointer true
bspc config normal_border_color \#262727
bspc config focused_border_color \#f5d1c8
bspc config active_focused_border_color \#f5d1c8
bspc config border_width 4
bspc config window_gap 20

### BSPWM Rules ###
bspc rule -a Scratchpad sticky=on state=floating
bspc rule -a Bottom state=floating
bspc rule -a discord desktop='2'
