#!/usr/bin/env sh

help() {
	echo '	-m,			make a new sink'
	echo '	-l,			list current sinks'
	echo '	-u,			remove sink'
}

makesink() {
	echo "Enter Main Sink Name"
	read main_sink_name;
	pactl load-module module-null-sink sink_name="$main_sink_name" sink_properties=device.description="$main_sink_name"
	pactl load-module module-loopback latency_msec=1 source=$main_sink_name.monitor sink=bluez_sink.CC_A7_C1_FF_CC_91.a2dp_sink
	
	echo "Enter Music Sink Name"
	read music_sink_name;
	pactl load-module module-null-sink sink_name="$music_sink_name" sink_properties=device.description="$music_sink_name"
	pactl load-module module-loopback latency_msec=1 source=$music_sink_name.monitor sink=bluez_sink.CC_A7_C1_FF_CC_91.a2dp_sink
}

listsinks() {
	pactl list short sinks
}

unloadsink() {
	echo "Enter Module Number (1/4)"
	read modulenum;
	pactl unload-module $modulenum

	echo "Enter Module Number (2/4)"
	read modulenum;
	pactl unload-module $modulenum

	echo "Enter Module Number (3/4)"
	read modulenum;
	pactl unload-module $modulenum

	echo "Enter Module Number (4/4)"
	read modulenum;
	pactl unload-module $modulenum
}

case "$1" in
	-m) makesink;;
	-l) listsinks;;
	-u) unloadsink;;
	*) help;;
esac
