#!/usr/bin/env bash

### Display Setup
xrandr --output DP-1 --primary --mode 1920x1080 --rate 144.00 &
# xrandr --output DP-1 --primary --mode 1920x1080 --rate 144.00 --output HDMI-1 --mode 1920x1080 --rate 60.00 --right-of DP-2 &

### Disable Screen Timeout ###
xset -dpms;
xset s off &
