#!/usr/bin/env sh

getwindow() {
xprop -id $(xprop -root '\t$0' _NET_ACTIVE_WINDOW | cut -f 2) '\t$0' WM_NAME | cut -f 2 | sed -e 's/.//' -e 's/.$//'
}

window=$(getwindow)

if [ $window = M_NAM ]; then
	echo 'LeftWM'
else
	getwindow
fi
