#!/usr/bin/env sh

### Use xinput list to find pointer name

xinput --set-prop 'pointer:''Logitech USB Receiver Mouse' 'libinput Accel Profile Enabled' 0, 1
xinput --set-prop 'pointer:''Logitech USB Receiver Mouse' 'libinput Accel Speed' 0
