#!/usr/bin/env sh

print_notification() {
  content=$(echo "$1" | tr '\n' ' ')
  content="(label :limit-width 27 :text '$content')"
  echo "{\"show\": $2, \"content\": \"$content\"}"
}

#print_notification "" "false"
#tiramisu -o '#summary' | while read -r line; do 
#  print_notification "$line" "true"
#  kill "$pid" 2> /dev/null
#  (sleep 10; print_notification "$line" "false") &
#  pid="$!"
#
#  mpv /usr/share/sounds/freedesktop/stereo/message.oga
#done

mpv /usr/share/sounds/freedesktop/stereo/message.oga
