#!/bin/sh

areashot () {	
	maim -usb 2 /tmp/screenshot.png; sleep .1; xclip -selection clipboard < /tmp/clipboard.png -t image/png && notify-send -i /tmp/screenshot.png 'Screenshot' 'Selection Copied'
}

fullshot () {
	maim -usb 2 /mnt/HDD/Images/Screenshots/clipboard.png; sleep .1; notify-send -i /mnt/HDD/Images/Screenshots/screenshot.png 'Screenshot' 'Selection Saved'
}

while getopts af flag; do
	case "$flag" in
		a) areashot;;
		f) fullshot;;
	esac
done

mpv /usr/share/sounds/freedesktop/stereo/camera-shutter.oga
