#!/bin/sh

areashot () {	
	maim -usb 2 /tmp/screenshot.png || exit 1;
	sleep .1;
	xclip -selection clipboard < /tmp/screenshot.png -t image/png
	dunstify -i /tmp/screenshot.png 'Screenshot' 'Selection Copied'
	mpv /usr/share/sounds/freedesktop/stereo/camera-shutter.oga
}

fullshot () {
	maim -usb 2 /mnt/HDD/Images/Screenshots/screenshot.png || exit 1;
	sleep .1;
	dunstify -i /mnt/HDD/Images/Screenshots/screenshot.png 'Screenshot' 'Selection Saved'
	mpv /usr/share/sounds/freedesktop/stereo/camera-shutter.oga
}

case "$1" in
	-a) areashot;;
	-f) fullshot;;
esac

