#!/bin/sh

getvol() {
	amixer -D pulse sget Master | grep 'Left:' | awk -F'[][]' '{ print $2 }' | tr -d '%'
}

getvolsym() {
	checkmute=$(amixer -D pulse sget Master | grep 'Front Left:' | awk -F'[][]' '{ print $4 }')
	
	if [ $checkmute != on ]; then
		echo ''
	else
		if [ $(getvol) -lt 30 ]; then
			echo ''
		else
			if [ $(getvol) -lt 40 ]; then
				echo ''
			else
				if [ $(getvol) -lt 50 ]; then
					echo '墳'
				else
					if [ $(getvol) -ge 50 ]; then
						echo ''
					fi
				fi
			fi
		fi
	fi
}

volumebar () {
  # This is for 5
  full=""
  half=""
  empty=""
  volume=$(~/scripts/getvol)
  total_half_dots=$(( $(echo ${volume} / 10 | cut -f1 -d ".") ))
  half_dots=$(( ${total_half_dots} % 2 ))
  full_dots=$(( ( ${total_half_dots} - $(( ${total_half_dots} % 2 )) ) / 2))
  empty_dots=$(( 5 - ( ${full_dots} + half_dots ) ))
	bar=$(echo $(echo $(seq -s " " $((${full_dots}+1)) )$(seq -s " " $((${half_dots}+1)) )$(seq -s " " $(($empty_dots + 1)) ) ) | sed 's/[0-9]//g')

	echo $bar
}

volup () {	
	amixer -D pulse sset Master 5%+
	notify-send "$(getvolsym) Volume" "$(volumebar)" -i none
	mpv /usr/share/sounds/freedesktop/stereo/audio-volume-change.oga
}

voldown () {
	amixer -D pulse sset Master 5%-
	notify-send "$(getvolsym) Volume" "$(volumebar)" -i none
	mpv /usr/share/sounds/freedesktop/stereo/audio-volume-change.oga
}

volmute () {
	amixer -D pulse sset Master toggle
}

while getopts vsudm flag; do
	case "$flag" in
		v) getvol;;
		s) getvolsym;;
		u) volup;;
		d) voldown;;
		m) volmute;;
	esac
done
