#!/bin/sh

getvol() {
	~/scripts/getvol
}

volup () {	
	amixer -D pulse sset Master 5%+
	notify-send Volume -h int:value:$(getvol)
}

voldown () {
	amixer -D pulse sset Master 5%-
	notify-send Volume -h int:value:$(getvol)
}

volmute () {
	amixer -D pulse sset Master toggle
}

while getopts udm flag; do
	case "$flag" in
		u) volup;;
		d) voldown;;
		m) volmute;;
	esac
done

mpv /usr/share/sounds/freedesktop/stereo/audio-volume-change.oga
