#!/usr/bin/env bash

run() {
	if ! pgrep -f "$1"; then
		"$@"&
	fi
}

### Mouse ###
run solaar --window=hide

### Wallpaper ###
# run ~/scripts/wallpapersetter

### Compositor ###
run picom

### Bluetooth ###
run blueman-applet

### Emacs ###
run emacs --daemon

### Discord ###
if pgrep -f discord; then
	exit &
else
	discocss &
fi
