#!/usr/bin/env bash

run() {
	if ! pgrep -f "$1"; then
		"$@"&
	fi
}

### Screen ###
run ~/scripts/display-setup

### Mouse ###
run solaar --window=hide
# run ~/scripts/mousesettings

### Wallpaper ###
# run ~/scripts/wallpapersetter

### Compositor ###
run picom

### Bluetooth ###
run blueman-applet

### Discord ###
if pgrep -f discord; then
	exit &
else
	discocss &
fi

### Emacs ###
# if pgrep -f emacs; then
# 	exit &
# else
# 	emacs --daemon &
# fi
